# The configuration for checking this files in this repo when checking the files locally.

log_level: INFO

rules:
  # Check for trailing whitespace and add a suggestion for how to remove it.
  - path_pattern: '^.'
    diff_pattern: '^.*\s+$'
    vote: REJECT
    comment: "Please remove the trailing whitespace in order to simplify the change and ensure that future automated formatting does not change this line."
    comment_id: "remove trailing whitespace"
    is_draft: false
    merge_status_pattern: '(?i)^(?!conflicts)'
    suggestions:
      - pattern: '\s+$'
        replacement: ''